# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=models.TextField(default='iiiiiiiiii'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='major',
            field=models.CharField(default='iiiiiiiiiiiiiii', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='professor',
            field=models.CharField(default='iiii', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='selectd',
            field=models.BooleanField(default=False),
        ),
    ]
