# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170325_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='selectd',
            new_name='selected',
        ),
    ]
